// This file is auto-generated by yamls2go.go
package embeddedyamls

const (
	Crds_submariner_io_submariners_crd_yaml = `apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: submariners.submariner.io
spec:
  group: submariner.io
  names:
    kind: Submariner
    listKind: SubmarinerList
    plural: submariners
    singular: submariner
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Submariner is the Schema for the submariners API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: SubmarinerSpec defines the desired state of Submariner
          properties:
            broker:
              type: string
            brokerK8sApiServer:
              type: string
            brokerK8sApiServerToken:
              type: string
            brokerK8sCA:
              type: string
            brokerK8sRemoteNamespace:
              type: string
            ceIPSecDebug:
              type: boolean
            ceIPSecIKEPort:
              type: integer
            ceIPSecNATTPort:
              type: integer
            ceIPSecPSK:
              type: string
            clusterCIDR:
              type: string
            clusterID:
              type: string
            colorCodes:
              type: string
            count:
              format: int32
              type: integer
            debug:
              type: boolean
            namespace:
              type: string
            natEnabled:
              type: boolean
            repository:
              type: string
            serviceCIDR:
              type: string
            version:
              type: string
          required:
          - broker
          - brokerK8sApiServer
          - brokerK8sApiServerToken
          - brokerK8sCA
          - brokerK8sRemoteNamespace
          - ceIPSecDebug
          - ceIPSecPSK
          - clusterCIDR
          - clusterID
          - count
          - debug
          - namespace
          - natEnabled
          - serviceCIDR
          type: object
        status:
          description: SubmarinerStatus defines the observed state of Submariner
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
`
	Operator_yaml = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: submariner-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: submariner-operator
  template:
    metadata:
      labels:
        name: submariner-operator
    spec:
      serviceAccountName: submariner-operator
      containers:
        - name: submariner-operator
          # Replace this with the built image name
          image: quay.io/submariner/submariner-operator:0.0.2
          command:
          - submariner-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "submariner-operator"
`
	Role_yaml = `apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: submariner-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - submariner-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
- apiGroups:
  - submariner.io
  resources:
  - '*'
  verbs:
  - '*'
`
	Role_binding_yaml = `kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: submariner-operator
subjects:
- kind: ServiceAccount
  name: submariner-operator
roleRef:
  kind: Role
  name: submariner-operator
  apiGroup: rbac.authorization.k8s.io
`
	Service_account_yaml = `apiVersion: v1
kind: ServiceAccount
metadata:
  name: submariner-operator
`
)
